spring:
  data:
    redis:
      host: localhost
      port: 6380
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        index: default-index
        dimensions: 3072
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.5-flash
      fallback-models:
        - gemini-2.5-pro
        - gemini-2.0-flash-exp
      embedding:
        options:
          model: gemini-embedding-001
